sudo: required
dist: trusty

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

install:
  - ./gradlew assemble

script:
  - ./gradlew check

